sprint5/step1
marktol/react-burger pull request #7
Opened 2023-07-27 10:21 UTC by marktol

2023-07-27 11:18 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/IxyweHyL6ZJM7A> - нужно убрать консоль логи, и устранить ошибки в консоли;

- <https://disk.yandex.com/i/oJtNoWGSSEMIcg> - нужно поправить верстку в соответствии с макетом;

- Нужно поправить ссылки в хедере, активной должна быть только та, на которой сейчас находиться пользователь;

- Для страницы `/feed` нужно использовать сокет соединение `wss://norma.nomoreparties.space/orders/all`, а на странице `/profile/orders` - `wss://norma.nomoreparties.space/  orders`;

- <https://disk.yandex.com/i/SKdaMKEQMx_Ccw> - страница должна иметь роут `/profile/orders`, а не `/orders`;

- У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/6N0_ekBlAJOqVA> - это можно проверить в девтулс, во вкладке `networks`.

- Не отображается информация о заказе, если открыть маршрут `profile/orders/:id` в новой вкладке, хотя похожий функционал `/feed/:id` у вас работает корректно.

- <https://disk.yandex.com/i/DfbtcmONCWSt8w> - В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива.

- в приложении не должно быть `console.log` (допускается выводить ошибки).

- Вам нужно проверить запросы, некоторые их них (`GET /auth/user`, `POST /order`, `PATCH /user`) должны посылать `accessToken`. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

  Вы должны делать проверку на истечение токена, если токен истёк, вы должны получить новый, и снова сделать запрос.

  Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
  Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

  Для этого используйте обертку над fetch, примерно такую

  ```js
  // например вот так
  export const fetchWithRefresh = async (url, options) => {
    try {
      const res = await fetch(url, options);
      return await checkResponse(res);
    } catch (err) {
      if (err.message === 'jwt expired') {
        const refreshData = await refreshToken();
        if (!refreshData.success) {
          Promise.reject(refreshData);
        }
        localStorage.setItem('refreshToken', refreshData.refreshToken);
        setCookie('accessToken', refreshData.accessToken);
        options.headers.authorization = refreshData.accessToken;
        const res = await fetch(url, options);
        return await checkResponse(res);
      } else {
        return Promise.reject(err);
      }
    }
  };

  // использование

  export const postIngredients = arrayIngredients => {
    return fetchWithRefresh(`${URL}/orders`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json;charset=utf-8',
        authorization: getCookie('token'),
      },
      body: JSON.stringify({
        ingredients: data,
      }),
    }).then(data => {
      if (data?.success) return data;
      return Promise.reject(data);
    });
  };
  ```

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **После исправления всех замечаний, работа будет принята)**

2023-07-27 11:18 UTC, ArslanMustafin commented on src/Components/Feed/Feed.tsx
> +  };
**Можно лучше:**

тут лучше попробовать сделать это через `useMemo`. 
```js
const {ordersReady, ordersReady} = useMemo(...)
```

2023-07-27 11:18 UTC, ArslanMustafin commented on src/Components/Feed/Feed.tsx
> +export const FeedCard = (order: any) => {
**Надо исправить:**

Отдельные части страницы лучше вынести в отдельный компонент и отдельный файл

2023-07-27 17:12 UTC, marktol commented
Механизм который в последнем пунтке есть в профайле, остальное вроде поправил

2023-07-30 04:21 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно поправить ссылки в хедере, активной должна быть только та, на которой сейчас находиться пользователь;

- Не отображается информация о заказе, если открыть маршрут `profile/orders/:id` в новой вкладке <https://disk.yandex.com/i/aCdykkB0wf_QEw>, тоже самое касается и `/feed`.

- Если кликнуть на заказ в `/profile/orders`, должно открываться модальное окно, такое же как и в `/feed`.

- Вам нужно проверить запросы, некоторые их них (`GET /auth/user`, `POST /order`, `PATCH /user`) должны посылать `accessToken`. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

  Вы должны делать проверку на истечение токена, если токен истёк, вы должны получить новый, и снова сделать запрос.

  Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
  Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

  Для этого используйте обертку над fetch, примерно такую

  ```js
  // например вот так
  export const fetchWithRefresh = async (url, options) => {
    try {
      const res = await fetch(url, options);
      return await checkResponse(res);
    } catch (err) {
      if (err.message === 'jwt expired') {
        const refreshData = await refreshToken();
        if (!refreshData.success) {
          Promise.reject(refreshData);
        }
        localStorage.setItem('refreshToken', refreshData.refreshToken);
        setCookie('accessToken', refreshData.accessToken);
        options.headers.authorization = refreshData.accessToken;
        const res = await fetch(url, options);
        return await checkResponse(res);
      } else {
        return Promise.reject(err);
      }
    }
  };

  // использование

  export const postIngredients = arrayIngredients => {
    return fetchWithRefresh(`${URL}/orders`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json;charset=utf-8',
        authorization: getCookie('token'),
      },
      body: JSON.stringify({
        ingredients: data,
      }),
    }).then(data => {
      if (data?.success) return data;
      return Promise.reject(data);
    });
  };
  ```

2023-07-30 04:22 UTC, ArslanMustafin commented
> Механизм который в последнем пунтке есть в профайле, остальное вроде поправил

Увидел, но эта проверка нужна в 3 запросах), а у вас есть только в 1. Поэтому всё же нужно поправить))

2023-07-30 18:21 UTC, marktol commented
Пытался через предложенную функцию, но для этого мне надо переписываать много кода(час потратил и понял что еще много чего исправлять надо), поэтому просто сделал функцию с проверкой токена перед отправкой запросов с токеном.

2023-07-30 18:23 UTC, marktol commented
@ArslanMustafin  если можешь, проверь плс сегодня, чтобы я не переводился в другую группу)

2023-07-31 03:49 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-07-31 03:49 UTC, ArslanMustafin commented on src/Components/OrderFromHistory/OrderFromHistory.tsx
> +      <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-07-31 03:49 UTC, ArslanMustafin commented on src/Components/OrderFromHistory/OrderFromHistory.tsx
> +  } else {
**Можно лучше:**

При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен не будет:

```js
if (someCondition) {
  return value;
}
return data;
```

Такой подход называется "ранний возврат" <https://habr.com/ru/post/348074/>

2023-07-31 03:49 UTC, ArslanMustafin commented on src/Components/Order/Order.tsx
> +  });
**Рекомендую исправить:**

Вы должны указать зависимости, чтобы соединение не открывалось несколько раз, при каждом рендере.

2023-07-31 21:00 UTC, merged